# index:
#    path: /
#    controller: App\Controller\CountryController::index
controllers:
  resource: ../src/Controller/HomeController.php
  type:     annotation
  prefix:   /

# redirecting the homepage
homepage:
  path: /home
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /home
    permanent: true 