#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

trendingVideo:
  path: /trendingVideo
  controller: App\Controller\TrendingVideoController::index